apiVersion: v1
kind: Pod
metadata:
  name: example-volume-test-zfs-retain
  namespace: default
spec:
  containers:
  - name: example-volume-test-zfs-retain
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: example-local-zfs-pvc-retain
