apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
spec:
  nodeName: {node_name}
  restartPolicy: Never
  hostNetwork: true
  containers:
  - name: {pod_name}
    image: {image}
    #imagePullPolicy: IfNotPresent
    imagePullPolicy: Always
    args: []
    # TODO: add args
    env:
    - name: ZFS_PROVISIONER_LOG_LEVEL
      value: {log_level}

    securityContext:
      privileged: true

    volumeMounts:
    - name: dataset-mount-dir
      mountPath: {dataset_mount_dir}
      mountPropagation: Bidirectional

  volumes:
  - name: dataset-mount-dir
    hostPath:
      path: {dataset_mount_dir}
      type: DirectoryOrCreate
