apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: "{provisioner_name}"
  name: {pv_name}
spec:
  accessModes:
  - {access_mode}
  capacity:
    storage: {storage}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {pvc_name}
    namespace: {pvc_namespace}
  local:
    path: {local_path}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {selected_node_name}
  persistentVolumeReclaimPolicy: {reclaim_policy}
  storageClassName: {storage_class_name}
  volumeMode: {volume_mode}
