# TODO: not implememted yet
kind: ConfigMap
apiVersion: v1
metadata:
  name: zfs-provisioner-config
  namespace: kube-system
data:
  config.json: |-
    {
       "node_dataset_map": {
          "__default__": "chaos/data/zfs-provisioner",
          "that-other-node": "tank/zfs-provisioner"
       }
    }
