apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
spec:
  nodeName: {node_name}
  restartPolicy: Never
  containers:
  - name: {pod_name}
    image: busybox
    imagePullPolicy: IfNotPresent
    args:
    - sleep
    - "20"
